// src/lib/components/layout/PlayerDialog.svelte
<script lang="ts">
  import { clsx } from 'clsx';

  import ModeIcon from '../ui/ModeIcon.svelte';

  import { Dialog, Icon } from '$lib/components';
  import type { PlayerDetail } from '$lib/types';
  import { ITEMS } from '$lib/util/constants';
  import { arrowLeftIcon, gnomeIcon, searchIcon } from '$lib/util/icon';

  let players: Record<string, PlayerDetail> = $state({});
  let unsyncedPlayers: Array<string> = $state([]);
  let selectedItems: Array<string> = $state([]);
  let title = $state('Group Members');

  let dialog: Dialog;

  const onShowUniques = (player: string, uniques: Array<string>) => {
    selectedItems = uniques;
    title = `${player}'s Unique Collections`;
  };

  /**
   * Open the dialog.
   * @param {Record<string, PlayerDetail>} playersDetail Record containing players and their statistics.
   */
  export const open = (playersDetail: Record<string, PlayerDetail>, unsyncedPlayersDetail: Array<string>) => {
    players = playersDetail;
    unsyncedPlayers = unsyncedPlayersDetail;

    dialog.open();
  };
</script>

{#snippet iconSnippet()}
  <img
    class="w-6 h-6"
    alt="Members"
    src={gnomeIcon}
  />
{/snippet}

{#snippet returnSnippet()}
  <button
    class={clsx(
      'flex items-center justify-center w-6 h-6 border-2 border-black bg-linear-to-r from-button-start-stop to-button-end-stop',
      !selectedItems.length && 'hidden'
    )}
    aria-label="close"
    onclick={() => {
      selectedItems = [];
      title = 'Group Members';
    }}
  >
    <Icon
      class="w-6 h-6 text-black"
      title="close"
      path={arrowLeftIcon}
    />
  </button>
{/snippet}

<Dialog
  bind:this={dialog}
  controls={returnSnippet}
  icon={iconSnippet}
  {title}
>
  {#if selectedItems.length}
    <ul class="text-xl w-full">
      {#each selectedItems as selectedItem, i (selectedItem)}
        <li class="flex items-center gap-2 px-2 even:bg-primary-50">
          <div class={`sprite-icon id_${selectedItem}`}></div>

          <span>{ITEMS[selectedItem]}</span>
        </li>
      {/each}
    </ul>
  {:else}
    <div class="flex flex-col w-full whitespace-nowrap overflow-auto">
      <div class="sticky top-0 grid grid-cols-4 text-xl px-2 border-b-2 border-grey-50 text-white bg-primary-300">
        <span class="flex justify-center">Member</span>
        <span class="flex justify-center">Collections</span>
        <span class="flex justify-center">Uniques</span>
        <span class="flex justify-center">Mode</span>
      </div>

      {#if Object.keys(players).length}
        <ul class="text-xl w-full">
          {#each Object.entries(players).sort((a, b) => a[0].localeCompare(b[0])) as [player, { items, uniques }] (player)}
            <li class="px-2 even:bg-primary-50">
              <div class="grid grid-cols-4 text-xl">
                <div class="flex items-center justify-between gap-2">
                  <span>{player}</span>
                </div>

                <span class="flex justify-end">{items.length}</span>

                <div class="flex gap-2 justify-end">
                  <span>{uniques.length}</span>

                  {#if uniques.length > 0}
                    <button
                      aria-label="Search"
                      onclick={() => {
                        onShowUniques(player, uniques);
                      }}
                    >
                      <Icon
                        class="w-4 h-4"
                        title="Search"
                        path={searchIcon}
                      />
                    </button>
                  {/if}
                </div>

                <div class="flex items-center justify-end">
                  <ModeIcon {player} />
                </div>
              </div>
            </li>
          {/each}
        </ul>
      {:else}
        <span class="text-xl">Search for a group to view members</span>
      {/if}

      {#if unsyncedPlayers.length}
        <details class="open:[&>summary]:border-b-2">
          <summary class="sticky top-0 text-xl px-2 cursor-pointer border-t-2 border-grey-50 bg-primary-300 text-white"
            >{`Unsynced members (${unsyncedPlayers.length})`}</summary
          >
          <ul class="text-xl w-full">
            {#each unsyncedPlayers.sort((a, b) => a.localeCompare(b)) as unsyncedPlayer (unsyncedPlayer)}
              <li class="flex items-center justify-between gap-2 px-2 even:bg-primary-50">
                <span>{unsyncedPlayer}</span>

                <ModeIcon player={unsyncedPlayer} />
              </li>
            {/each}
          </ul>
        </details>
      {/if}
    </div>
  {/if}
</Dialog>

// src/components/dialog/PlayerDialog.tsx
import { Icon, IconButton, ModeIcon } from '@components';
import { Dialog } from '@components/dialog/Dialog';

import { useGroup } from '@hooks/useGroup';

import type { ItemDetail } from '@types';

import { bifilter } from '@utils/common';
import { arrowLeftIcon, searchIcon } from '@utils/icon';

import { useMemo, useState } from 'react';

interface FocusedPlayer {
  gameMode: number;
  name: string;
  uniques: Array<ItemDetail>;
}

export const PlayerDialog = () => {
  const [focusedPlayer, setFocusedPlayer] = useState<FocusedPlayer | null>(null);

  const { players } = useGroup();

  const [unsyncedPlayers, syncedPlayers] = useMemo(
    /**
     * Filter and sort synced players.
     */
    () =>
      bifilter(
        Object.values(players).sort((a, b) => +a.isSynced - +b.isSynced || a.name.localeCompare(b.name)),
        ({ isSynced }) => isSynced
      ),
    [players]
  );

  return (
    <Dialog
      title={focusedPlayer ? `${focusedPlayer.name}'s Unique Collections` : 'Group Members'}
      onClose={() => setFocusedPlayer(null)}
      controls={
        focusedPlayer && (
          <IconButton
            title="Return"
            path={arrowLeftIcon}
            onClick={() => setFocusedPlayer(null)}
          />
        )
      }
      icon={
        <ModeIcon
          gameMode={focusedPlayer ? focusedPlayer.gameMode : 0}
          minMode={0}
        />
      }
    >
      {focusedPlayer ? (
        <ul className="text-xl w-full">
          {focusedPlayer.uniques
            .sort((a, b) => a.name.localeCompare(b.name))
            .map(({ item, name }) => (
              <li
                key={item}
                className="flex items-center gap-2 px-2 even:bg-primary-50"
              >
                <div className={`sprite-icon id_${item}`}></div>

                <span>{name}</span>
              </li>
            ))}
        </ul>
      ) : (
        <div className="flex flex-col w-full whitespace-nowrap overflow-auto">
          <div className="sticky top-0 grid grid-cols-4 text-xl px-2 border-b-2 border-grey-50 text-white bg-primary-300">
            <span className="flex justify-center">Member</span>
            <span className="flex justify-center">Collections</span>
            <span className="flex justify-center">Uniques</span>
            <span className="flex justify-center">Game Mode</span>
          </div>

          <ul className="text-xl w-full">
            {syncedPlayers.map(({ name, gameMode, totalItemsCollected, uniques }) => (
              <li
                key={name}
                className="px-2 grid grid-cols-4 text-xl even:bg-primary-50"
              >
                <span>{name}</span>

                <span className="flex justify-end">{totalItemsCollected}</span>

                <div className="flex gap-2 justify-end">
                  <span>{uniques.length}</span>

                  {uniques.length > 0 && (
                    <button onClick={() => setFocusedPlayer({ gameMode, name, uniques })}>
                      <Icon
                        className="w-4 h-4"
                        title="Show uniques"
                        path={searchIcon}
                      />
                    </button>
                  )}
                </div>

                <div className="flex items-center justify-end">
                  <ModeIcon gameMode={gameMode} />
                </div>
              </li>
            ))}

            <li className="px-2 grid grid-cols-4 text-xl text-white even:bg-primary-50">
              <span>-</span>
              <span className="flex justify-end">
                {syncedPlayers.reduce((acc, { totalItemsCollected }) => acc + totalItemsCollected, 0)}
              </span>
              <span className="flex justify-end">{syncedPlayers.reduce((acc, { uniques }) => acc + uniques.length, 0)}</span>
              <span className="flex justify-end">-</span>
            </li>
          </ul>

          {unsyncedPlayers.length > 0 && (
            <details className="open:[&>summary]:border-b-2">
              <summary className="sticky top-0 text-xl px-2 cursor-pointer border-t-2 border-grey-50 bg-primary-300 text-white">
                {`Unsynced members (${unsyncedPlayers.length})`}
              </summary>

              <ul className="text-xl w-full">
                {unsyncedPlayers.map(({ name, gameMode }) => (
                  <li
                    key={name}
                    className="flex items-center justify-between gap-2 px-2 even:bg-primary-50"
                  >
                    <span>{name}</span>

                    <ModeIcon gameMode={gameMode} />
                  </li>
                ))}
              </ul>
            </details>
          )}
        </div>
      )}
    </Dialog>
  );
};
